#!/usr/bin/env bash
#install nginx server

# Update packages
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Allow the server to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Create a simple "Hello World!" index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Start the Nginx service
sudo service nginx start
