#!/usr/bin/env bash
#printing hours and minutes

Hour=0
while [ $Hour -le 12 ]
do
	echo "Hour: $Hour"
	counter=1
	while [ $counter -le 59 ]
	do
		echo "$counter"
		counter=$((counter + 1))
	done
	Hour=$((Hour + 1))
done

