#!/usr/bin/env bash
#printing hours and minutes

Hour=0
echo "Hour: $Hour"
while [ $Hour -le 11 ]
do
	counter=1
	while [ $counter -le 59 ]
	do
		echo "$counter"
		counter=$((counter + 1))
	done
	Hour=$((Hour + 1))
	echo "Hour: $Hour"
done

